# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

# - main
# trigger:


variables:
  - group: study_sign_vars
  - name: job_name
    value: 'build_test_vars'

pool:
  vmImage: 'macos-latest'

steps:

- task: JavaToolInstaller@0
  inputs:
    versionSpec: '11'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'assemble'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    sonarQubeRunAnalysis: false
    spotBugsAnalysis: false

- task: AndroidSigning@3
  inputs:
     apkFiles: '**/*.apk'
     apksignerKeystoreFile: 'studydev'
     apksignerKeystorePassword: '$(key_store_password)'
     apksignerKeystoreAlias: '$(key_alias)'
     apksignerKeyPassword: '$(key_password)'
- task: CopyFiles@2
  inputs:
    Contents: '**/*.apk'
    TargetFolder: '$(build.artifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'output'
    publishLocation: 'Container'

- task: AppCenterDistribute@3
  inputs:
    serverEndpoint: 'app center'
    appSlug: 'DevWorkStudy/DevStudyApp'
    appFile: '**/*.apk'
    symbolsOption: 'Android'
    releaseNotesOption: 'input'
    releaseNotesInput: 'New version realse'
    destinationType: 'groups'

# jobs:
# - job:
#   variables:
#   - group: study_sign_vars
#   - name: job_name
#     value: 'build_test_vars'
#   steps:
#   - task: AndroidSigning@3
#     inputs:
#      apkFiles: '**/*.apk'
#      apksignerKeystoreFile: 'studydev'
#      apksignerKeystorePassword: 'key_store_password'
#      apksignerKeystoreAlias: 'key_alias'
#      apksignerKeyPassword: 'key_password'


# steps:

# - task: JavaToolInstaller@0
#   inputs:
#     versionSpec: '11'
#     jdkArchitectureOption: 'x64'
#     jdkSourceOption: 'PreInstalled'

# # - task: Gradle@3
# #   inputs:
# #     gradleWrapperFile: 'gradlew'
# #     tasks: 'assembleDebug'
# #     publishJUnitResults: false
# #     testResultsFiles: '**/TEST-*.xml'
# #     javaHomeOption: 'JDKVersion'
# #     jdkVersionOption: '1.11'
# #     sonarQubeRunAnalysis: false
# #     spotBugsAnalysis: false

# # - task: JFrogGradle@1
# #   inputs:
# #     gradleBuildFile: 'build.gradle'
# #     tasks: 'presentation:artifactoryPublish'
# #     artifactoryResolverService: 'Study artifactory'
# #     sourceRepo: 'study-gradle-dev'
# #     artifactoryDeployerService: 'Study artifactory'
# #     targetRepo: 'study-gradle-dev-local'
# #     usesPlugin: true
# #     useWrapper: true
# #     deployIvyDesc: false


# - task: JFrogGradle@1
#   inputs:
#     gradleBuildFile: 'build.gradle'
#     tasks: 'presentation:artifactoryPublish'
#     artifactoryDeployerService: 'Study artifactory'
#     targetRepo: 'study-gradle-dev-local'
#     useWrapper: true
#     usesPlugin: true
#     deployIvyDesc: false

# - task: JFrogGradle@1
#   inputs:
#     gradleBuildFile: 'build.gradle'
#     tasks: 'network:artifactoryPublish'
#     artifactoryDeployerService: 'Study artifactory'
#     targetRepo: 'study-gradle-dev-local'
#     useWrapper: true
#     usesPlugin: true
#     deployIvyDesc: false

# # - task: JFrogGradle@1
# #   inputs:
# #     gradleBuildFile: 'build.gradle'
# #     tasks: 'artifactoryPublish'
# #     artifactoryResolverService: 'Study artifactory'
# #     sourceRepo: 'study-gradle-dev'
# #     artifactoryDeployerService: 'Study artifactory'
# #     targetRepo: 'study-gradle-dev-local'


# # - task: CopyFiles@2
# #   inputs:
# #     Contents: '**/*.apk'
# #     TargetFolder: '$(build.artifactStagingDirectory)'

# # - task: PublishBuildArtifacts@1
# #   inputs:
# #     PathtoPublish: '$(Build.ArtifactStagingDirectory)'
# #     ArtifactName: 'output'
# #     publishLocation: 'Container'

# # - task: AppCenterDistribute@3
# #   inputs:
# #     serverEndpoint: 'app center'
# #     appSlug: 'DevWorkStudy/DevStudyApp'
# #     appFile: '$(Build.ArtifactStagingDirectory)/app/build/outputs/apk/debug/app-debug.apk'
# #     symbolsOption: 'Android'
# #     releaseNotesOption: 'input'
# #     releaseNotesInput: 'New version realse'
# #     destinationType: 'groups'
