# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- develop

pool:
  vmImage: 'macos-latest'

steps:
- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'assembleRelease'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    sonarQubeRunAnalysis: false
    spotBugsAnalysis: false


- task: CopyFiles@2
  inputs:
    Contents: '**/*.apk'
    TargetFolder: '$(build.artifactStagingDirectory)'


- task: CmdLine@2
  inputs:
    script: mv $(Build.ArtifactStagingDirectory)/app/build/outputs/apk/release/app-release-unsigned.apk
      $(build.artifactstagingdirectory)/app/build/outputs/apk/release/app-release.apk


- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/app/build/outputs/apk/release/app-release.apk'
    ArtifactName: 'output'
    publishLocation: 'Container'